<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IP3P31F" failures="2" tests="3" name="MY Test" time="1.08" errors="0" timestamp="2021-02-28T19:31:15 IST">
  <testcase classname="test.NewTest" name="firstTest" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [sac1hin] but found [sachin]">
      <![CDATA[java.lang.AssertionError: expected [sac1hin] but found [sachin]
at test.NewTest.firstTest(NewTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.runner.Runner.main(Runner.java:14)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- firstTest -->
  <testcase classname="test.NewTest" name="secondTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [sac1hin] but found [sachin]">
      <![CDATA[java.lang.AssertionError: expected [sac1hin] but found [sachin]
at test.NewTest.secondTest(NewTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.runner.Runner.main(Runner.java:14)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- secondTest -->
  <testcase classname="test.NewTest2" name="firstTest" time="0.0"/>
</testsuite> <!-- MY Test -->
